version: '3.8'

networks:
  mysql-phpmyadmin:
    name: mysql-phpmyadmin
    # use the bridge driver
    driver: bridge

services:
  back_supcup:
    build: .
    ports:
     - "5001:5001"
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: thispasswordneedachange
      MYSQL_DATABASE: supcup_db
      MYSQL_USER: supcup_user
      MYSQL_PASSWORD: supcup_password
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata: